plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/nishimuraemiri/ward-management-app/.claude/worktrees/romantic-mcclintock/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/nishimuraemiri/ward-management-app/.claude/worktrees/romantic-mcclintock"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]