import {abxCumDay,groupSchedule,pendingOccurrences,elapsedDay,imageCellStatus} from './scheduleLogic.js';
import {useState} from 'react';
import {dateKey,parseDate,shortDate,occurrenceDone} from './dates.js';
import AntibioticEditor from './AntibioticEditor.jsx';
import LabCalculator from './LabCalculator.jsx';
const specimens=['血液','尿','喀痰','髄液','胸水','腹水'];
const names={abx:'抗菌薬',med:'内服',drip_main:'点滴',lab:'採血',img:'画像',culture:'培養',meeting:'面談',consult:'他科依頼',family_call:'家族連絡',rehab_call:'リハ連絡',msw_call:'MSW連絡'};
export function OrderEditor({patient,order,onSave,onDelete,onClose}) {
 const [patientDraft,setPatientDraft]=useState({...patient});
 const [draft,setDraft]=useState({...order,dates:[...(order.dates||[])]});
 const [date,setDate]=useState('');
 const [error,setError]=useState('');
 const set=(k,v)=>setDraft(p=>({...p,[k]:v}));
 function save(){const savedDates=draft.type!=='abx'&&date?[...new Set([...draft.dates,date])].sort():draft.dates;if(date&&!parseDate(date)){setError('日付を確認してください。');return;}if(patientDraft.age!==''&&patientDraft.age!=null&&(!Number.isInteger(Number(patientDraft.age))||Number(patientDraft.age)<0||Number(patientDraft.age)>139)){setError('年齢は0〜139の整数で入力してください。');return;}if(draft.type==='abx'&&draft.startDate&&draft.endDate&&draft.endDate<draft.startDate){setError('終了日は開始日以降にしてください。');return;}if(draft.type==='abx'&&!draft.name){setError('抗菌薬を選択、または薬剤名を入力してください。');return;}onSave({...draft,dates:savedDates,confirmations:Object.fromEntries(Object.entries(draft.confirmations||{}).filter(([date])=>savedDates.includes(date)))},patientDraft.age===''||patientDraft.age==null?'':Number(patientDraft.age));onClose();}
 return <div className="modal-shade"><section className="ward-dialog" role="dialog" aria-modal="true" aria-labelledby="order-title"><h2 id="order-title">{patient.name}・予定の編集</h2>
 <label>種類<select value={draft.type} onChange={e=>set('type',e.target.value)}>{!names[draft.type]&&<option value={draft.type}>{draft.type}</option>}{Object.entries(names).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>
 {draft.type==='abx'?<><div className="field-grid"><label>開始日<input type="date" value={draft.startDate||''} onInput={e=>set('startDate',e.currentTarget.value)} onChange={e=>set('startDate',e.target.value)}/></label><label>終了日<input type="date" value={draft.endDate||''} onInput={e=>set('endDate',e.currentTarget.value)} onChange={e=>set('endDate',e.target.value)}/></label></div><AntibioticEditor patient={patientDraft} order={draft} onChange={setDraft} onAgeChange={age=>setPatientDraft(p=>({...p,age}))}/></>:<>
 {draft.type!=='culture'&&<label>予定の名称<input value={draft.name||''} onChange={e=>set('name',e.target.value)}/></label>}
 {draft.type==='culture'&&<><label>培養の名称<select aria-label="培養の名称" value={draft.specimen==='痰'?'喀痰':draft.specimen||''} onChange={e=>setDraft(p=>({...p,specimen:e.target.value,name:e.target.value}))}><option value="">選択してください</option>{specimens.map(v=><option key={v} value={v}>{v}</option>)}{draft.specimen&&!specimens.includes(draft.specimen)&&draft.specimen!=='痰'&&<option value={draft.specimen}>{draft.specimen}（既存）</option>}</select></label><label>グラム染色・結果メモ<input value={draft.gramResult||''} onChange={e=>set('gramResult',e.target.value)}/></label></>}
 <p className="muted">日付を入力して保存できます。複数日は「日付を追加」で登録してください。</p><label>日付を追加<input type="date" value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><button onClick={()=>{if(date&&!draft.dates.includes(date)){set('dates',[...draft.dates,date].sort());setDate('');}}}>日付を追加</button>
 {draft.dates.map(d=><div className="agenda-order" key={d}><div>{d}</div><button onClick={()=>set('dates',draft.dates.filter(x=>x!==d))}>日付を外す</button>{['img','culture'].includes(draft.type)&&<button onClick={()=>set('confirmations',{...draft.confirmations,[d]:!occurrenceDone(draft,d)})}>{occurrenceDone(draft,d)?'確認済み・戻す':'結果を確認済みに'}</button>}</div>)}
 {draft.regWeekday!=null&&<p>定期処方：毎週{'日月火水木金土'[draft.regWeekday]}曜日。日付は処方済みの日を記録します。</p>}
 </>}
 {error&&<p role="alert">{error}</p>}
 <footer><button onClick={onClose}>キャンセル</button>{onDelete&&<button onClick={()=>{onDelete();onClose();}}>削除</button>}<button className="primary" onClick={save}>保存</button></footer></section></div>;
}
export default function ScheduleAgenda({patients,orders,date,onDate,onEditPatient,onEditOrder,onAddOrder,labs,onLabs,onDischarge,onRegular,onChecklist,onHiddenCategories,onDateCell,categories={},labFields=[]}) {
 const [compact,setCompact]=useState(true);
 const [categoryPatient,setCategoryPatient]=useState(null);
 const [enlarged,setEnlarged]=useState(false);
 const [labPatient,setLabPatient]=useState(null);
 const start=new Date(date);start.setDate(start.getDate()-((start.getDay()+6)%7));
 const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});
 const key=dateKey(date);
 const move=n=>{const d=new Date(date);d.setDate(d.getDate()+n);onDate(d);};
 return <div className={"schedule-agenda"+(compact?" compact-schedule":"")}><div className="agenda-nav"><button aria-label="前の週" onClick={()=>move(-7)}>‹</button><strong>{date.getFullYear()}年 {shortDate(days[0])}–{shortDate(days[6])}</strong><button aria-label="次の週" onClick={()=>move(7)}>›</button><button onClick={()=>onDate(new Date())}>今日</button></div>
 <div className="schedule-switch"><strong>週間一覧</strong><button aria-pressed={compact} onClick={()=>setCompact(!compact)}>{compact?"ゆったり表示":"一覧をコンパクトに"}</button><button aria-pressed={enlarged} onClick={()=>setEnlarged(!enlarged)}>{enlarged?'全体表示':'拡大表示'}</button></div>
 <p className="muted weekly-help">7日分の一覧です。日付を押すと予定を付け外しできます。名称を押すと詳細編集。抗菌薬は開始日→終了日の順に押して期間を設定します。</p><div className="weekly-scroll"><div className={'weekly-board'+(enlarged?' enlarged':'')}>
 <div className="weekly-grid weekly-head"><strong>患者・予定</strong>{days.map(d=><span key={dateKey(d)} className={dateKey(d)===dateKey(new Date())?'weekly-today':''}>{'日月火水木金土'[d.getDay()]}<b>{d.getDate()}</b></span>)}</div>
 {patients.map(p=><section className="weekly-patient" key={p.id}><div className="weekly-grid weekly-patient-heading"><button aria-label={`${p.name}の患者情報`} onClick={()=>onEditPatient(p)}><small>{p.room}</small><b>{p.name}</b></button>{days.map(d=>{const k=dateKey(d);return <span key={k}>{(p.admitDateISO||p.admitDate)===k&&<small>入院</small>}{(p.plannedDischargeDate||p.dischargePlan)===k&&<small>退院予定</small>}{p.surgery===k&&<small>手術</small>}</span>;})}</div>
 {groupSchedule(orders[p.id]||[],categories[p.id]).filter(cat=>!(p.hiddenScheduleTypes||[]).includes(cat.type)).map(cat=><section className="weekly-category" key={cat.type} aria-label={`${p.name}・${cat.label}`}><div className="weekly-category-heading"><strong><span aria-hidden="true">{cat.icon}</span> {cat.label}</strong><button aria-label={`${p.name}の${cat.label}を追加`} onClick={()=>onAddOrder(p,cat.type)}>＋追加</button></div>
 {cat.items.length===0&&<button className="weekly-empty" onClick={()=>onAddOrder(p,cat.type)}>予定なし・追加</button>}
 {cat.items.map(o=><div className="weekly-grid weekly-order" key={o.id} data-order-label={`${p.name}・${(o.type==='culture'?o.specimen||o.name:o.name||o.specimen)||names[o.type]||'予定'}を編集`}><button className="weekly-label" aria-label={`${p.name}・${o.specimen||o.name||names[o.type]}を編集`} onClick={()=>onEditOrder(p,o)}><b>{((o.type==='culture'?o.specimen||o.name:o.name||o.specimen))===cat.label?'予定日':(o.type==='culture'?o.specimen||o.name:o.name||o.specimen)||'名称未入力'}</b>{o.regWeekday!=null&&<small>毎週{'日月火水木金土'[o.regWeekday]}曜</small>}</button>{days.map(d=>{const k=dateKey(d),bar=o.startDate&&k>=o.startDate&&(!o.endDate||k<=o.endDate),point=o.dates?.includes(k),regular=o.regWeekday===d.getDay(),covered=o.regWeekday!=null&&(o.dates||[]).some(v=>{const start=parseDate(v);if(!start)return false;const end=new Date(start);end.setDate(end.getDate()+6);return k>=v&&k<=dateKey(end);});const imageStatus=imageCellStatus(o,k,dateKey(new Date()));const pending=o.type==='img'?[]:pendingOccurrences(o,k),day=pending.length?elapsedDay(pending[0],k):null;return <button aria-label={`${p.name}・${o.specimen||o.name||names[o.type]}・${k}の予定`} aria-pressed={!!(bar||point)} onClick={()=>o.type==='img'&&point?onEditOrder(p,o):onDateCell(p,o,k,o.type==='abx'||(cat.isBar&&!['med','drip_main'].includes(o.type))||!!o.startDate)} title={imageStatus==='pending'?'この日の画像レポートが未確認です。押して確認結果を記録':pending.map(v=>`${shortDate(v)}実施：${o.type==='img'?'レポート未確認':elapsedDay(v,k)+'日目・未確認'}`).join(' / ')} key={k} className={'weekly-cell'+(k===dateKey(new Date())?' weekly-today':'')+(imageStatus==='pending'?' image-awaiting':'')}><span className={bar?'weekly-bar':covered?'weekly-prescription':''}>{imageStatus==='pending'?<>未<small>確認</small></>:bar?(o.type==='abx'?<>{abxCumDay(orders[p.id],o,k)||elapsedDay(o.startDate,k)}<small>日目</small></>:'━'):pending.length?<span className="pending-day">{o.type==='img'?<>未<small>確認{pending.length>1?`・${pending.length}件`:''}</small></>:<>{day}<small>日目{pending.length>1?`・${pending.length}件`:''}</small></>}</span>:point?(occurrenceDone(o,k)?'✓':'●'):regular?'○':covered?'─':''}</span></button>;})}</div>)}</section>)}
 {!(orders[p.id]||[]).length&&<p className="muted">登録予定はありません</p>}
 <div className="weekly-patient-actions"><button onClick={()=>setCategoryPatient(p)}>表示項目{p.hiddenScheduleTypes?.length?`（${p.hiddenScheduleTypes.length}項目非表示）`:""}</button><button onClick={()=>onAddOrder(p)}>＋予定</button><button onClick={()=>onRegular(p.id)}>定期処方</button><button onClick={()=>onChecklist(p,'a')}>入院TODO</button><button onClick={()=>onChecklist(p,'d')}>退院TODO</button><details><summary>その他</summary><div className="agenda-actions"><button onClick={()=>setLabPatient(p)}>検査・TSAT・RPI</button>{p.plannedDischargeDate&&<button onClick={()=>onDischarge(p.id)}>退院の実施を確認</button>}</div></details></div>
 </section>)}
 </div></div><p className="muted">帯：抗菌薬の通算日数　橙色の日数：培養の未確認（採取日を1日目）　画像：実施日のマスを確認まで強調（押して結果確認）　●：予定・処方済み　○：定期処方日　✓：結果確認済み</p>
 {patients.length===0&&<p>表示する患者がいません。</p>}
 {categoryPatient&&<div className="modal-shade"><section className="ward-dialog" role="dialog" aria-modal="true" aria-label="表示項目"><h2>{categoryPatient.name}・表示項目</h2><p className="muted">チェックを外すと週間表のコーナーを隠します。登録済みの予定と「今日」の通知は残ります。</p>{groupSchedule(orders[categoryPatient.id]||[],categories[categoryPatient.id]).map(cat=><label key={cat.type} style={{display:'flex',alignItems:'center',gap:12,minHeight:44}}><input type="checkbox" style={{width:24,minHeight:24}} checked={!(categoryPatient.hiddenScheduleTypes||[]).includes(cat.type)} onChange={e=>{const hidden=e.target.checked?(categoryPatient.hiddenScheduleTypes||[]).filter(t=>t!==cat.type):[...(categoryPatient.hiddenScheduleTypes||[]),cat.type];setCategoryPatient(p=>({...p,hiddenScheduleTypes:hidden}));onHiddenCategories(categoryPatient.id,hidden);}}/>{cat.icon} {cat.label}（{cat.items.length}件）</label>)}<footer><button onClick={()=>setCategoryPatient(null)}>閉じる</button></footer></section></div>}
 {labPatient&&<div className="modal-shade"><section className="ward-dialog" role="dialog" aria-modal="true" aria-label="検査の計算"><h2>{labPatient.name}</h2><details><summary>その他の検査値</summary><p className="muted">施設の単位で記録してください。基準範囲による自動判定は行いません。</p><div className="field-grid">{labFields.map(f=><label key={f.id}>{f.l}<input value={labs[labPatient.id]?.[f.id]?.value||""} onChange={e=>onLabs(labPatient.id,{...labs[labPatient.id],[f.id]:{...labs[labPatient.id]?.[f.id],value:e.target.value}})}/></label>)}</div></details><LabCalculator value={labs[labPatient.id]} onChange={v=>onLabs(labPatient.id,v)}/><footer><button onClick={()=>setLabPatient(null)}>閉じる</button></footer></section></div>}
 </div>;
}
